[package]
name = "SPR"
version = "0.1.0"
edition = "2021"

[dependencies]
num = "0.4.1"
time = "0.3.29"
petgraph = "0.6.4"
regex = "1.10.2"
rand = "0.8.5"
csv = "1.3.0"
pest = "2.7.4"

[dependencies.newick_parser]
path = "../newick_parser"